path:
  - [ -0.8289, 0.7, 0.2500 ]
  - [  0.6447, 0.7, 0.6912 ]
  - [  1.7500, 0.7, 1.8676 ]
  - [  1.0132, 0.7, 2.7500 ]
  - [ -0.4605, 0.7, 2.4559 ]
  - [ -1.7500, 0.7, 1.5735 ]
  - [ -1.3816, 0.7, 0.3971 ]
  - [ -0.8289, 0.7, 0.2500 ]
